### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DeadZen**
Spotted a couple typos

### CODE REVIEW

**Comment by srgg** [comment]
@DeadZen can you please add your changes to the https://github.com/basho/spark-riak-connector/pull/29

**Comment by mjbrender** [comment]
Hey @srgg - can't we merge #29 then merge #30? Minor difference to the log and less work for our community member who put in the effort to help. cc @mdigan

**Comment by mdigan** [comment]
Agreed. Let's merge #29 and then merge #30.

**Comment by mdigan** [comment]
#29 is now merged. I'll merge this one now. Thanks for your contribution @DeadZen !

**Comment by mdigan** [comment]
Closing. Typos ended up getting fixed as part of other PRs. Thanks again for your contribution @DeadZen

**Pull request closed without merging**
